service: default
runtime: python
env: standard
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.7

manual_scaling:
  instances: 1

endpoints_api_service:
  name: endpointsportal.mlai-trial-project-work.cloud.goog
  config_id: CONFIG_ID

env_variables:
    # The app will look for the model file at: gs://MODEL_BUCKET/MODEL_FILENAME
    MODEL_BUCKET: mlai-trial-project-work.appspot.com
    MODEL_FILENAME: DeepJ_model_111.h5